language: R
cache: packages
sudo: true
cran: https://cloud.r-project.org

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - _R_CHECK_SYSTEM_CLOCK_=false
    - NOT_CRAN=true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'install.packages("remotes", ask = FALSE)'
  - Rscript -e 'remotes::install_version(package = "RSpectra", version = "0.13-1", upgrade = "never")'

r_github_packages:
  - r-lib/covr
  - gabraham/flashpca/flashpcaR

bioc_packages:
  - IlluminaHumanMethylation450kmanifest
  - IlluminaHumanMethylationEPICmanifest

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::coveralls(); covr::codecov()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: 3.5
  - r: 3.6

after_success:
  - Rscript -e 'covr::coveralls(); covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
