# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap


# Adapt as necessary starting from here
version: 0.3.0.{build}


environment:
  global:
    USE_RTOOLS: true
    _R_CHECK_FORCE_SUGGESTS_: false
    BIOC_USE_DEVEL: FALSE
    NOT_CRAN: true

build_script:
  - travis-tool.sh install_bioc IlluminaHumanMethylation450kmanifest
  - travis-tool.sh install_bioc IlluminaHumanMethylationEPICmanifest
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps
  - Rscript -e "install.packages('remotes', repos = 'http://cran.us.r-project.org');"
  - Rscript -e "remotes::install_github(repo = 'gabraham/flashpca/flashpcaR')"

test_script:
#  - travis-tool.sh run_tests
  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org');"
  - Rscript -e "remotes::install_github(repo = 'mcanouil/CARoT')"
  - Rscript -e "devtools::check()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bit
